# Site settings
title: Bunny's Blog
email: amy@amyboyd.co.uk
description: >
    I'm a full-stack developer, and this is my blog.
baseurl: "/blog"
url: "http://amyboyd.co.uk"
twitter_username: CoderBunny
github_username:  amyboyd

# Build settings
markdown: kramdown
